### ISSUE TITLE
question: browser implementation

### ISSUE THREAD

**Issue by joshhjacobson** [mljs/random#2]
Hi there,

I'm working on a library / es6 module that is bundled with rollup and used to build web-apps. I'm using your ml-kmeans module in one of the functions as follows:
```javascript
const result = kmeans(values, k);
```
Rollup can successfully build the module, but when I run a browser demo using the function I've written I get the console error `Uncaught ReferenceError: require is not defined`  which references this line from `index.ts`:
```javascript
const XSAdd = require('ml-xsadd');
```
I understand that this is because `require()` does not exist in the browser. In that sense, what is the recommended method to use this library if it will be running in the browser?

Also, why not just import `XSAdd` like the other functions, i.e.
```javascript
import XSAdd from 'ml-xsadd';
```
I think this would solve my issue.

Cheers,
Josh

**Comment by stropitek** [comment]
Hello,

The package `ml-xsadd` only exists as a commonjs package. Therefore it cannot be loaded using the es6 module syntax.

Can you try using this rollup plugin to convert commonjs modules to es6 modules?

https://github.com/rollup/rollup-plugin-commonjs

**Comment by stropitek** [comment]
Other possibility is to support es6 modules in ml-xsadd

We'd gladly accept a PR that adds support for es6 modules without breaking commonjs support.

https://github.com/mljs/xsadd/issues/2

**Comment by joshhjacobson** [comment]
Thanks for the quick response! I've tried the commonjs plugin but I still get the same error. Here is my configuration:
```javascript
resolve({
     module: true,
     jsnext: true,
     main: true,
     browser: true,
     extensions: ['.js', '.ts']
}),
commonjs({
     include: [
       'node_modules/ml-random/lib-es6/index.ts', 
       'node_modules/ml-distance-euclidean/**', 
       'node_modules/ml-nearest-vector/**'
     ],
     namedExports: {
       'node_modules/ml-distance-euclidean/euclidean.js': ['euclidean', 'squared'],
     }
}),
```
If you notice an error here, let me know. Otherwise, I'll work on adding support for es6 modules to `ml-xsadd`, and maybe `ml-distance-euclidean` as well.

**Comment by joshhjacobson** [comment]
Looks like this was addressed in v0.5.0, thanks! I'll close the issue.

**Comment by stropitek** [comment]
@joshhjacobson 
I just published kmeans@4.2.0 where all dependencies export es6 modules so you should be able to build your bundle without using the plugin.

Let us know if it works

**Comment by joshhjacobson** [comment]
@stropitek 
Just tested kmeans@4.2.0 and I'm still getting an error related to the issue I posted in that repo mljs/kmeans#13. Here it is:
```
[!] Error: 'default' is not exported by node_modules/ml-distance-euclidean/lib-es6/euclidean.js
npm ERR! code ELIFECYCLEp/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
npm ERR! errno 1kmeans/src/kmeans.js (1:7)
```
This is because `ml-distance-euclidean/lib-es6/euclidean.js` has two exports, but kmeans.js references a default. To fix, `ml-distance-euclidean/lib-es6/euclidean.js` should define variables for the functions then export them in an object, and the import statement in kmeans.js should be
```javascript
import { euclidean } from 'ml-distance-euclidean';
```
I'd be happy to submit pull requests with these changes if you'd like.

**Comment by joshhjacobson** [comment]
Fixed with mljs/kmeans#13. Cheers!
